name: Run Node.js Server with Express

on:
    push:
        branches:
            - main

jobs:
    build-and-run:
        runs-on: ubuntu-latest
        
        steps:
            - name: Installing Dependencies
              run: |
                sudo apt update
                sudo apt install nodejs
                node -v
                sudo apt install nodejs
                node -v
            
            - name: Running Node.js server
              run: node server.js