name: Run Node.js Server with Express

on:
    push:
        branches:
            - main

jobs:
    build-and-run:
        runs-on: ubuntu-latest
        
        steps:
            - name: Installing Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install nodejs
                node -v
                sudo apt-get install npm
                npm -v
            
            - name: Debug info
              run: |
                pwd
                ls -al
            
            - name: Running Node.js server
              run: node server.js